---
- name: Change Password for Root User
  vars:
    user_data: "{{ lookup('file', '../setup/uservar') }}"
    new_pass: "{{ lookup('file', '../setup/newpass') }}"
  hosts: vm1-{{user_data}}:vm2-{{user_data}}
  become: yes
  gather_facts: yes

  tasks:
    - name: Install python3-pexpect (Debian)
      apt:
        name: python3-pexpect
        state: latest
      when: ansible_distribution == 'Debian'    
    - name: Install python3-pexpect (RedHat)
      yum:
        name: python3-pexpect
        state: latest
      when: ansible_distribution == 'RedHat'

    - name: Change root password
      expect:
        command: passwd root
        responses:
          'New password:*': "{{new_pass}}\n"
          'Retype new password:*': "{{new_pass}}\n"
      become: yes

    - name: Display success message
      debug:
        msg: "Password for root user changed successfully on {{ inventory_hostname }}"

