---
  - name: Replace Files (ansible.cfg and hosts)
    vars:
      user_data: "{{ lookup('file', '../setup/uservar') }}"
 #   hosts: vm1-{{user_data}}:vm2-{{user_data}}
 #   become: yes
 #   tasks:
 #     - name: Copy sshd_config file to vm1 and vm2    
 #       copy:
 #         src: ../replaceFiles/sshd_config
 #         dest: /etc/ssh/sshd_config
    hosts: ansible-server-{{user_data}}
    become: yes
    tasks:   
      - name: Copy new hosts to ansible vm
        copy:
          src: ../replaceFiles/hosts/hosts-{{user_data}} 
          dest: /etc/ansible/hosts
      - name: Copy ansible.cfg file
        copy:
          src: ../replaceFiles/ansible.cfg
          dest: /etc/ansible/ansible.cfg
