---
  - name: Replace Files
    vars:
      user_data: "{{ lookup('file', '../setup/uservar') }}"
    hosts: vm1-{{user_data}}:vm2-{{user_data}}
    become: yes
    tasks:
      - name: Copy sshd_config file to vm1 and vm2    
        copy:
          src: ../replaceFiles/sshd_config
          dest: /etc/ssh/sshd_config    
