---
  - name: Get apache webapp set up/updated with swollenhippofinal file from github repo on VM1 & VM2
    vars:
      user_data: "{{ lookup('file', '../setup/uservar') }}"
    hosts: vm1-{{user_data}}:vm2-{{user_data}}
    tasks:
       - name: Copy and Execute the script 
         script: ../bash-scripts/swollenhippofinal-deploy-apache.sh
